language: node_js

cache:
  directories:
  - node_modules
node_js:
  - "4"
  - "6"
  - "8"
  - "10"
  - "12"
  - "13"
  - "14"
  - "15"
  - "16"
sudo: required
services: docker
before_install:
  - if [[ "$TRAVIS_OS_NAME" == "linux" && "$TRAVIS_BUILD_STAGE_NAME" =~ Test.* ]]; then ./run_docker.sh; fi
  # - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install openssl; fi
  - if [[ "$TRAVIS_OS_NAME" == "windows" ]]; then ./win_install.bat; fi
install:
  - if [[ "$TRAVIS_BUILD_STAGE_NAME" =~ Test.* ]]; then npm install; fi

script:
  - if [[ "$TRAVIS_BUILD_STAGE_NAME" =~ Test.* ]]; then make lint && make test && make check; else echo $TRAVIS_BUILD_STAGE_NAME; fi

jobs:
  include:
    - stage: test_on_mac
      os: osx
      osx_image: xcode10
      env: CPPFLAGS=-I/usr/local/opt/openssl/include LDFLAGS=-L/usr/local/opt/openssl/lib
      node_js:
        - "10"
    - stage: test_on_win
      os: windows
      node_js:
        - "10"
    # - stage: create_doc
    #   provider: script
    #   before_deploy:
    #     - openssl aes-256-cbc -K $encrypted_a2e08d5c220e_key -iv $encrypted_a2e08d5c220e_iv -in deploy.enc -out /tmp/deploy -d
    #     - eval "$(ssh-agent -s)"
    #     - chmod 600 /tmp/deploy
    #     - ssh-add /tmp/deploy
    #   script:
    #     - "./make_docs.sh"
    #   if: (tag =~ ^v)
    - stage: deploy
      os: linux
      node_js:
        - "10"
      script: skip
      if: (tag =~ ^v)
      before_deploy:
      - npm install --no-save semver
      deploy:
        provider: npm
        skip_cleanup: true
        email: npm@ovt.me
        api_key:
          secure: "LEyXqiZURgmqSFH8vaGg48uqOBn5fjRFHgUGiK1wJizRfQdGxITxcBdWAqxgXQBKuRTjLAx+0/wnN8wTdnaQE772WMZa6rwid9lZ/7v8djtcjpaPKYGcHY5qqk8Zd9oVwj5nlIountWDWx3U/PMvIfOJyudMz6/yicMJczTKxqKkMQrOFoE34VH2eMfyBHWzYgjtXlBYr55ryrAom9zbd+6bD/jZOEAqR2YB1gpCANZR1W1mKgAd1q/8N89bhTwVYHS8sRo4QN8nghJarf02FikKWPKW6DhLFDoqP1+DsQBu2EIlwlmHa3iGmhK8y6WsuGlSzVejzstAn3N8/hQN19BGBn0foiABL6rfe9ONDjF3+LDGjWu7kPtrZ7I+b+iNzt6VzHHfr9R3M9L6ug1T1rtzJDRXyW8HhZdyGYxYgdMld1Hr62B6c06tHRtJgYjeaTfhkh54EN2FiL/e7CcfHDiU8mP3hoQsK00ev3qtySWi8H26BlaE2Wl13FYCvx+ITxjYgVCx93fh0VgrSHm9+wEOpaYlN/2s8N3ZHohRRlGyR68KFcoyRNuI4aOpCe9aeFSEybjBCVmRybGTwRVeDUw762DlHPScDeK5tYZabDJjxRLh3I9uj7Xd4W8LLq9xZdxZfrwQnb9H0cJWEQU8AXkoPA5oxB3F7tCpkiSjG/g=" 
        on:
          tags: true
      after_deploy:
        - cat package.json
